apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHMuY3AwdW1rOHVvMXkyLnVzLXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  db_username: YWRtaW4=
  db_password: bXlzZWN1cmVwYXNzd29yZA==
  db_name: Ym9va3NkYg==   # base64 for 'booksdb'


